name: Update rule set
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v3
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - name: Install dependencies
        id: install
        run: pip install -r requirements.txt
      - name: Check for New Commits
        id: checkcommit
        run: |
          yesterday=$(date -I -d yesterday)
          commit_count=$(curl -s "https://api.github.com/repos/dogfight360/UsbEAm/commits?since=${yesterday}T00:00:00Z" | jq '. | length')
          echo "commit_count=${commit_count}" >> $GITHUB_OUTPUT
      - name: Download rules
        id: download
        if: ${{ steps.checkcommit.outputs.commit_count > 0 }}
        run: curl -L -o UsbEAm.ini https://raw.githubusercontent.com/dogfight360/UsbEAm/master/Usbeam/usbeam_new_20.xml 
      - name: Update rules
        id: update
        if: ${{ steps.checkcommit.outputs.commit_count > 0 }}
        run: python src/UsbEAm2Clash.py
      - name: Commit changes
        id: commit
        if: ${{ steps.checkcommit.outputs.commit_count > 0 }}
        uses: EndBug/add-and-commit@v9
        with:
          message: Update UsbEAm rules
          default_author: github_actions