name: Update rule set
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download rules
        run: curl -L -o UsbEAm.ini https://usbeam.steam302.xyz/Usbeam/usbeam_new_20.xml
      - name: Download console rules
        run: curl -L -o UsbEAm_console.ini https://usbeam.steam302.xyz/Usbeam/usbeam_console.xml
      - name: Update rules
        run: python src/UsbEAm2Clash.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update UsbEAm rules
          default_author: github_actions
