name: Update rule set
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check for New Commits
        run: |
          yesterday=$(date -I -d yesterday)
          commits=$(curl -s "https://api.github.com/repos/dogfight360/UsbEAm/commits?since=${yesterday}T00:00:00Z")
          commit_count=$(echo ${commits} | jq 'if all(.[]; has("commit")) then length else 0 end'))
          echo "commit_count=${commit_count}" >> $GITHUB_OUTPUT
  update:
    runs-on: ubuntu-latest
    needs: check_commit
    if: ${{ needs.check_commit.outputs.commit_count > 0 }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download rules
        run: curl -L -o UsbEAm.ini https://raw.githubusercontent.com/dogfight360/UsbEAm/master/Usbeam/usbeam_new_20.xml 
      - name: Update rules
        run: python src/UsbEAm2Clash.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update UsbEAm rules
          default_author: github_actions
